### ISSUE TITLE
Error in jedi:install-server

### ISSUE THREAD

**Issue by spookylukey** [tkf/emacs-jedi#225]
I followed the installation instructions with the 'package.el' method. It installed  jedi-20150413.2208/
and jedi-core-20150422.209/ in my 'elpa' directory.

When I then execute `jedi:install-server`, I get the following error:

    Making virtualenv at /home/luke/.emacs.d/.python-environments/default...Done
    deferred error : (error "Process [virtualenv] exited abnormally : Traceback (most recent call last):
      File \"/home/luke/.local/bin/virtualenv\", line 9, in <module>
        load_entry_point('virtualenv==1.11.4', 'console_scripts', 'virtualenv')()
      File \"/usr/lib/python2.7/dist-packages/virtualenv.py\", line 825, in main
        symlink=options.symlink)
      File \"/usr/lib/python2.7/dist-packages/virtualenv.py\", line 993, in create_environment
        install_wheel(to_install, py_executable, search_dirs)
      File \"/usr/lib/python2.7/dist-packages/virtualenv.py\", line 961, in install_wheel
        'PIP_NO_INDEX': '1'
      File \"/usr/lib/python2.7/dist-packages/virtualenv.py\", line 903, in call_subprocess
        % (cmd_desc, proc.returncode))
    OSError: Command /home/luke/.emacs.d/...s/default/bin/python -c \"import sys, pip; sys...d\\\"] + sys.argv[1:]))\" setuptools pip failed with error code 1
    ")

If I attempt it again, I get the following message:

    Running: pip install --upgrade /home/luke/.emacs.d/elpa/jedi-core-20150422.209/...

But it doesn't seem to do anything.

Investigating the virtualenv that has been created in ~/.emacs.d/.python-environments/default, it seems a bit empty. It doesn't have an 'activate' script, and it doesn't have a 'pip' in the bin folder, so I can't even try to continue the installation manually.

**Comment by spookylukey** [comment]
OK, it looks like I have a problem with my `virtualenv` when run with `--system-site-packages`:

    Collecting setuptools
    Collecting pip
      Could not find a version that satisfies the requirement pip (from versions: 1.5debian1)
      No distributions matching the version for pip
    ----------------------------------------
    ...Installing setuptools, pip...done.
    Traceback (most recent call last):
      File "/home/luke/.local/bin/virtualenv", line 9, in <module>
        load_entry_point('virtualenv==1.11.4', 'console_scripts', 'virtualenv')()
      File "/usr/lib/python2.7/dist-packages/virtualenv.py", line 825, in main
        symlink=options.symlink)
      File "/usr/lib/python2.7/dist-packages/virtualenv.py", line 993, in create_environment
        install_wheel(to_install, py_executable, search_dirs)
      File "/usr/lib/python2.7/dist-packages/virtualenv.py", line 961, in install_wheel
        'PIP_NO_INDEX': '1'
      File "/usr/lib/python2.7/dist-packages/virtualenv.py", line 903, in call_subprocess
        % (cmd_desc, proc.returncode))
    OSError: Command /home/luke/.emacs.d/...nts/test1/bin/python -c "import sys, pip; sys...d\"] + sys.argv[1:]))" setuptools pip failed with error code 1

This seems to be some packaging bug was resolved for me by do `easy_install --prefix=$HOME/.local --upgrade virtualenv`.

Sorry for the noise, perhaps this will help someone else.
