### ISSUE TITLE
`jedi:setup` fails on initial loading of python file in emacs but succeeds on repeated trials.

### ISSUE THREAD

**Issue by se4u** [tkf/emacs-jedi#278]
I am encountering a strange error where `jedi` fails to start the EPC server when I first load a file in emacs and try autocompletion in it. So on initial loading of the file, I don't see any autocompletion results and I see the following warning: 

```
Error (jedi): Failed to start Jedi EPC server.
*** You may need to run "M-x jedi:install-server". ***
This could solve the problem especially if you haven't run the command yet
since Jedi.el installation or update and if the server complains about
Python module imports.
```

But when I manually call `jedi:install-server` and `jedi:setup` then sometimes I get a timeout error but sometimes both commands run successfull and I am able to see the completions: 

The following is an abbreviated version of the error, which seems to be due to a timeout
``` python
Traceback (most recent call last):
  File "/Users/pushpendrerastogi/.emacs.d/.python-environments/default/lib/python2.7/site-packages/pip/basecommand.py", line 223, in main
    status = self.run(options, args)
....
....
File "/Users/pushpendrerastogi/.emacs.d/.python-environments/default/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/connectionpool.py", line 314, in _raise_timeout
    if 'timed out' in str(err) or 'did not complete (read)' in str(err):  # Python 2.6
TypeError: __str__ returned non-string (type Error)
```

I was wondering if you had any idea about what might be going wrong?

**Comment by se4u** [comment]
I fixed this problem by moving to `elpy` and letting `elpy` handle the jedi configuration and interface. Everything is fine now afaict. So I am closing the issue now.
