### ISSUE TITLE
Failed to start Jedi EPC Server

### ISSUE THREAD

**Issue by yltozh** [tkf/emacs-jedi#312]
My jedi is showing these errors

```
Error (jedi): Failed to start Jedi EPC server.                                        
*** You may need to run "M-x jedi:install-server". ***                                
This could solve the problem especially if you haven't run the command yet            
since Jedi.el installation or update and if the server complains about                
Python module imports.  

deferred error : (error "Server may raise an error. Use \"M-x epc:pop-to-last-server-proc\
ess-buffer RET\" to see full traceback:                                                   
Traceback (most recent call last):                                                        
  File \"/home/ylto/.emacs.d/.python-environments/default/bin/jediepcserver\", line 11, i\
n <module>                                                                                
    sys.exit(main())                                                                      
  File \"/home/ylto/.emacs.d/.python-environments/default/lib/python3.5/site-packages/jed\
iepcserver.py\", line 321, in main                                                        
")  
```

then after I do M-x epc:pop-to-last-server-process-buffer

```
Traceback (most recent call last):                                                        
  File "/home/ylto/.emacs.d/.python-environments/default/bin/jediepcserver", line 11, in \
<module>                                                                                  
    sys.exit(main())                                                                      
  File "/home/ylto/.emacs.d/.python-environments/default/lib/python3.5/site-packages/jedi\
epcserver.py", line 321, in main                                                          
    server = jedi_epc_server(**vars(ns))                                                  
  File "/home/ylto/.emacs.d/.python-environments/default/lib/python3.5/site-packages/jedi\
epcserver.py", line 230, in jedi_epc_server                                               
    server = epc.server.EPCServer((address, port))                                        
  File "/home/ylto/.emacs.d/.python-environments/default/lib/python3.5/site-packages/epc/\
server.py", line 121, in __init__                                                         
    self, server_address, RequestHandlerClass, bind_and_activate)                         
  File "/usr/lib/python3.5/socketserver.py", line 440, in __init__                        
    self.server_bind()                                                                    
  File "/usr/lib/python3.5/socketserver.py", line 454, in server_bind                     
    self.socket.bind(self.server_address)                                                 
OSError: [Errno 99] Cannot assign requested address                                       
                                                                                          
Process epc:server:4 exited abnormally with code 1  

```

It cannot assign the requested address. Can anyone figure out what is wrong?

**Comment by immerrr** [comment]
@tree-fiddy 

What's your OS?
what does it say when you do `ping localhost`?
what does it say when you do `ping 127.0.0.1`?

**Comment by tree-fiddy** [comment]
@immerrr 

MacOS Mojave 10.14

`ping localhost` outputs:
64 bytes from 127.0.0.1: icmp_seq=0 ttl=64 time=0.042 ms
64 bytes from 127.0.0.1: icmp_seq=1 ttl=64 time=0.081 ms
64 bytes from 127.0.0.1: icmp_seq=2 ttl=64 time=0.072 ms
...
...

`ping 127.0.0.1` outputs the same thing.

In my hunt to remedy this jedi issue, I've messed around with so much, that I've opened up a pandora's box of errors.  Now, I am getting: 
```
deferred error : (error "Deferred process exited abnormally:
  command: virtualenv
  exit status: exit 127
```
which hangs up emacs for 30 seconds at a time, at random times.  I'm afraid I'll have to do a clean install of emacs and start my init.el from scratch.

**Comment by Prologueyan** [comment]
I have met same issue，have u solved it

**Comment by immerrr** [comment]
@Prologueyan not sure if the original reporter was able to fix this on their side, but there certainly were no additional fixes in the code.

Are you seeing the same error messages as originally reported? Do the messages change if you use the latest code from master branch?

**Comment by Prologueyan** [comment]
@immerrr  thanks ， I  solved this

**Comment by immerrr** [comment]
@Prologueyan would you be able to share what was the problem and how did you fix this so that people that come after you have more troubleshooting material to work with?

**Comment by Prologueyan** [comment]
I use flask to setup a web server ,but i forgot to change the ip address setting to my own machine.

**Comment by dariushazimi** [comment]
I have the same issue:
OS = Mac OS Catalina
python = 3.7
is there a solution for this?

thank you all.

Error (jedi): 
================================
Failed to start Jedi EPC server.
================================

*** EPC Error ***
Server may raise an error. Use "M-x epc:pop-to-last-server-process-buffer RET" to see full traceback:
No handlers could be found for logger "jediepcserver"


*** EPC Server Output (last 10 lines) ***
No handlers could be found for logger "jediepcserver"


*** EPC Server Config ***
Server arguments: ("/Users/darius/.emacs.d/.python-environments/default/bin/jediepcserver")
Actual command: /Users/darius/.emacs.d/.python-environments/default/bin/jediepcserver
VIRTUAL_ENV envvar: "/Users/darius/.local/share/virtualenvs/streamlittut-oarDHXSx"

*** jedi-mode is disabled in #<buffer app.py> ***
Fix the problem and re-enable it.

*** You may need to run "M-x jedi:install-server". ***
This could solve the problem especially if you haven't run the command yet
since Jedi.el installation or update and if the server complains about
Python module imports.

**Comment by immerrr** [comment]
@dariushazimi I believe your failure is different. What do you see if you run 
```
/Users/darius/.emacs.d/.python-environments/default/bin/jediepcserver
```
in your terminal?

**Comment by yefeiyu** [comment]
$ './.python-environments/default/bin/jediepcserver'
dyld: Library not loaded: @executable_path/../.Python
  Referenced from: /Users/darius/.emacs.d/.python-environments/default/bin/python3.7
  Reason: image not found
Abort trap: 6
