### ISSUE TITLE
Wrong shebang?

### ISSUE THREAD

**Issue by Dolgorbie** [tkf/emacs-jedi#346]
I have two Mac PCs whose version is 10.14.
I installed Jedi on one of my Macs a years ago
and installed Jedi on the other some days ago.
The older emacs-jedi system works well, but the newer doesn't.

I found a defference between them in ~/.emacs.d/.python-environments/default/bin/jediepcserver.
The shebang of that of correctly working system is:
#!/Users/username/.emacs.d/.python-environments/default/bin/python3.7
But that of broken is:
#!/usr/local/opt/python/bin/python3.7

I rewrote second shebang to first shebang.
Then the broken jedi worked.

**Comment by immerrr** [comment]
That shebang is overwritten by whatever python is used to install the jediepcserver script. 

In the repo the shebang is neither of the two values:

```
#!/usr/bin/env python
```

Do you have any way of knowing how was the newer jediepcserver installed?

**Comment by Dolgorbie** [comment]
I used the following emacs command:
`M-x jedi:install-server`

**Comment by iharsuvorau** [comment]
Have the same problem. @Dolgorbie suggestion solved the problem.

**Comment by immerrr** [comment]
@iharsuvorau @Dolgorbie could you share what are your `jedi:environment-root`, `python-environment-default-root-name` and `python-environment-directory`?

Also, when you say it doesn't work, could you please share what's the problem?

And finally, `jedi:show-version-info` and `jedi:show-setup-info` could also help.

Thank you!

**Comment by iharsuvorau** [comment]
@immerrr sure, thank you for debugging. Here is it:

Output of `jedi:show-setup-info`:

``` lisp
;; Emacs Lisp version:
(:emacs-version "26.3" :jedi-version "0.2.8" :python-environment-version "0.0.2alpha0")
;; Python version:
nil
;; EPC error:
(:get-epc-error
 (wrong-type-argument epc:manager nil))
;; Command line:
(:virtualenv "/usr/local/bin/virtualenv" :virtualenv-version "virtualenv 20.0.10 from /usr/local/lib/python3.7/site-packages/virtualenv/__init__.py\n")
;; Customization:
((jedi:complete-on-dot . t)
 (jedi:doc-display-buffer . display-buffer)
 (jedi:doc-hook view-mode)
 (jedi:doc-mode . rst-mode)
 (jedi:environment-root)
 (jedi:environment-virtualenv)
 (jedi:get-in-function-call-delay . 1000)
 (jedi:get-in-function-call-timeout . 3000)
 (jedi:goto-definition-config
  (nil nil nil)
  (t nil nil)
  (nil definition nil)
  (t definition nil)
  (nil nil t)
  (t nil t)
  (nil definition t)
  (t definition t))
 (jedi:goto-definition-hook)
 (jedi:goto-definition-marker-ring-length . 16)
 (jedi:imenu-create-index-function . jedi:create-nested-imenu-index)
 (jedi:import-python-el-settings . t)
 (jedi:install-imenu)
 (jedi:install-python-jedi-dev-command "pip" "install" "--upgrade" "git+https://github.com/davidhalter/jedi.git@master#egg=jedi")
 (jedi:key-complete .
		    [C-tab])
 (jedi:key-goto-definition .
			   [67108910])
 (jedi:key-goto-definition-pop-marker .
				      [67108908])
 (jedi:key-related-names . "r")
 (jedi:key-show-doc . "d")
 (jedi:server-args)
 (jedi:server-command "/Users/ihar/.emacs.d/elpa/jedi-core-20191011.1750/jediepcserver.py")
 (jedi:setup-keys)
 (jedi:tooltip-method pos-tip popup)
 (jedi:use-shortcuts)
 (python-environment-default-root-name . "default")
 (python-environment-directory . "~/.emacs.d/.python-environments")
 (python-environment-virtualenv "virtualenv" "--system-site-packages" "--quiet"))
```

I have the following errors:

```
================================
Failed to start Jedi EPC server.
================================

*** EPC Error ***
Server may raise an error. Use "M-x epc:pop-to-last-server-process-buffer RET" to see full traceback:
Traceback (most recent call last):
  File "/Users/ihar/.emacs.d/elpa/jedi-core-20191011.1750/jediepcserver.py", line 39, in <module>
    import jedi
ImportError: No module named jedi


*** EPC Server Output (last 10 lines) ***
Traceback (most recent call last):
  File "/Users/ihar/.emacs.d/elpa/jedi-core-20191011.1750/jediepcserver.py", line 39, in <module>
    import jedi
ImportError: No module named jedi


*** EPC Server Config ***
Server arguments: ("/Users/ihar/.emacs.d/elpa/jedi-core-20191011.1750/jediepcserver.py")
Actual command: /Users/ihar/.emacs.d/elpa/jedi-core-20191011.1750/jediepcserver.py
VIRTUAL_ENV envvar: nil

*** jedi-mode is disabled in #<buffer *jedi:show-setup-info*> ***
Fix the problem and re-enable it.

*** You may need to run "M-x jedi:install-server". ***
This could solve the problem especially if you haven't run the command yet
since Jedi.el installation or update and if the server complains about
```

and at the same time in the minibuffer:

```
jedi:epc--start-epc: Wrong type argument: epc:manager, nil
```

Running `M-x jedi:install-server` doesn't influence the situation, that's how the server was installed.

Running `jedi:show-version-info` throws the same error: couldn't start the server.
