### ISSUE TITLE
deferred error : (error "\"TypeError('__init__() ...

### ISSUE THREAD

**Issue by bcmarini** [tkf/emacs-jedi#353]
I'm getting the following error when I type anything into an open ".py"  file:
`deferred error : (error "\"TypeError('__init__() takes from 1 to 2 positional arguments but 5 positional arguments (and 1 keyword-on\
ly argument) were given')\"")`

From http://tkf.github.io/emacs-jedi/latest/#troubleshooting
1. Output of `M-x jedi:show-setup-info`:
```
(jedi:key-goto-definition .
                           [67108910])
 (jedi:key-goto-definition-pop-marker .
                                      [67108908])
 (jedi:key-related-names . "^Cr")
 (jedi:key-show-doc . "^Cd")
 (jedi:server-args)
 (jedi:server-command "/home/bruno/.emacs.d/.python-environments/default/bin/jediepcserver")
 (jedi:setup-keys)
 (jedi:tooltip-method pos-tip popup)
 (jedi:use-shortcuts)
 (python-environment-default-root-name . "default")
 (python-environment-directory . "~/.emacs.d/.python-environments")
 (python-environment-virtualenv "virtualenv" "--system-site-packages" "--quiet"))
```

3. `M-: jedi-mode` returns `t`

6. (should read 6) The traceback is as follows:
```
ERROR:epc:Unexpected error
Traceback (most recent call last):
  File "/home/bruno/.emacs.d/.python-environments/default/lib/python3.8/site-packages/epc/handler.py", line 242, in _handle
    reply = handler(uid, *args)
  File "/home/bruno/.emacs.d/.python-environments/default/lib/python3.8/site-packages/epc/utils.py", line 51, in new_method
    ret = method(self, *args, **kwds)
  File "/home/bruno/.emacs.d/.python-environments/default/lib/python3.8/site-packages/epc/handler.py", line 265, in _handle_call
    return ['return', uid, func(*args)]
  File "/home/bruno/.emacs.d/.python-environments/default/lib/python3.8/site-packages/jediepcserver.py", line 227, in get_in_functio\
n_call
    sig = self.jedi_script(*args).call_signatures()
  File "/home/bruno/.emacs.d/.python-environments/default/lib/python3.8/site-packages/jediepcserver.py", line 201, in jedi_script
    return jedi.Script(
TypeError: __init__() takes from 1 to 2 positional arguments but 5 positional arguments (and 1 keyword-only argument) were given
```

This is from a fresh install (OS, emacs and jedi). I only have Python3.8.5 installed. Emacs' version is 26.3 and this is my `.emacs` file:
```
(require 'package)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
(package-initialize)
;; jedi python                                                                                                                       
(add-hook 'python-mode-hook 'jedi:setup)
(setq jedi:complete-on-dot t)
(setq jedi:server-args '("--log-traceback"))
```

Installation was done without any error messages.

**Comment by bcmarini** [comment]
Got it working again after some changes:

File `jediepcserver.py`:
Changed the deprecated `completions()` to `complete()`
Line 223: `for comp in self.jedi_script(*args).complete()`

File `api/__init__.py` (with the Script class):
Line 101: `def __init__(self, code=None, line=None, column=None, path=None, environment=None, project=None):`

**Comment by paaguti** [comment]
Ubutnu 20.04 emacs28.2 from snap
Trying to setup company company-jedi environment.
Same error as reported here. Main difference
M-: jedi-mode returns nil
