### ISSUE TITLE
Failed to start Jedi EPC server.

### ISSUE THREAD

**Issue by matianhe3** [tkf/emacs-jedi#356]
```Error (jedi): 
Failed to start Jedi EPC server.
*** EPC Error ***
Server may raise an error. Use "M-x epc:pop-to-last-server-process-buffer RET" to see full traceback:
Traceback (most recent call last):
  File "/Users/matianhe/.emacs.d/elpa/jedi-core-20210202.856/jediepcserver.py", line 40, in <module>
    import jedi
ImportError: No module named jedi

*** EPC Server Output (last 10 lines) ***
Traceback (most recent call last):
  File "/Users/matianhe/.emacs.d/elpa/jedi-core-20210202.856/jediepcserver.py", line 40, in <module>
    import jedi
ImportError: No module named jedi

*** EPC Server Config ***
Server arguments: ("/usr/bin/python" "/Users/matianhe/.emacs.d/elpa/jedi-core-20210202.856/jediepcserver.py")
Actual command: /usr/bin/python
VIRTUAL_ENV envvar: nil

*** jedi-mode is disabled in #<buffer chandao.py> ***
Fix the problem and re-enable it.

*** You may need to run "M-x jedi:install-server". ***
This could solve the problem especially if you haven't run the command yet
since Jedi.el installation or update and if the server complains about
Python module imports.
```

show-setup-info:
```
;; Emacs Lisp version:
(:emacs-version "27.1" :jedi-version "0.3.0" :python-environment-version "0.0.2alpha0")
;; Python version:
nil
;; EPC error:
(:get-epc-error
 (wrong-type-argument epc:manager nil))
;; Command line:
(:virtualenv nil :virtualenv-version nil)
;; Customization:
((jedi:complete-on-dot . t)
 (jedi:doc-display-buffer . display-buffer)
 (jedi:doc-hook view-mode)
 (jedi:doc-mode . rst-mode)
 (jedi:environment-root)
 (jedi:environment-virtualenv)
 (jedi:get-in-function-call-delay . 1000)
 (jedi:get-in-function-call-timeout . 3000)
 (jedi:goto-definition-config
  (nil nil nil)
  (t nil nil)
  (nil definition nil)
  (t definition nil)
  (nil nil t)
  (t nil t)
  (nil definition t)
  (t definition t))
 (jedi:goto-definition-hook)
 (jedi:goto-definition-marker-ring-length . 16)
 (jedi:imenu-create-index-function . jedi:create-nested-imenu-index)
 (jedi:import-python-el-settings . t)
 (jedi:install-imenu)
 (jedi:install-python-jedi-dev-command "pip" "install" "--upgrade" "git+https://github.com/davidhalter/jedi.git@master#egg=jedi")
 (jedi:key-complete .
		    [C-tab])
 (jedi:key-goto-definition .
			   [67108910])
 (jedi:key-goto-definition-pop-marker .
				      [67108908])
 (jedi:key-related-names . "r")
 (jedi:key-show-doc . "d")
 (jedi:server-args)
 (jedi:server-command "python" "/Users/matianhe/.emacs.d/elpa/jedi-core-20210202.856/jediepcserver.py")
 (jedi:setup-keys)
 (jedi:tooltip-method pos-tip popup)
 (jedi:use-shortcuts)
 (python-environment-default-root-name . "default")
 (python-environment-directory . "~/.emacs.d/.python-environments")
 (python-environment-virtualenv "virtualenv" "--system-site-packages" "--quiet"))
```
OS: mac OS X 11.2.1 (20D74)

```
python 2.7:
which python
/usr/bin/python

python 3.8:
 which python3
/usr/bin/python3

 which pip
/Users/matianhe/Library/Python/3.8/bin/pip

 which virtualenv
/Users/matianhe/Library/Python/3.8/bin/virtualenv

pip list |grep jedi
jedi              0.18.0
```

in my init.el:
```
(setq python-shell-interpreter "/usr/bin/python3")
(setq py-python-command "/usr/bin/python3") 
(setq python-python-command "/usr/bin/python3")
```
it also :
`(jedi:server-command "python" "/Users/matianhe/.emacs.d/elpa/jedi-core-20210202.856/jediepcserver.py")`

**Comment by paaguti** [comment]
Can confirm this on my setup. Additional tests:
```
~ ➤ python -c 'import jedi'                                                    
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named jedi
~ ➤ python3 -c 'import jedi'  
~ ➤
```
